# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml

modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="MIT"
issueTrackerURL="https://github.com/yahaha5788/create-handcrafted/issues"

[[mods]] #mandatory

modId="createhandcrafted" #mandatory
version="0.0.0" #mandatory
displayName="Create: Handcrafted" #mandatory
displayURL="https://github.com/yahaha5788/create-handcrafted"

logoFile="createhandcrafted.png" #optional
#credits=""
authors="yahaha, Astro_Gamer" #optional

description='''Have you ever thought the crafting table was too omnipowerful?
That a handful of alloy shouldn't become a solid basin in the palm of your hands?
Create: Handcrafted puts you through the full process to make that part.
While it will be more work, you will find it all the more powerful in the end.
Precision, makes perfect.
'''

[[dependencies.createhandcrafted]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.createhandcrafted]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

#[[dependencies.createhandcrafted]]
#    modId="create"
#    mandatory=true
#    versionRange="[0.5.1,)"
#    ordering="NONE"
#    side="BOTH"

# Features are specific properties of the game environment, that you may want to declare you require. This example declares
# that your mod requires GL version 3.2 or higher. Other features will be added. They are side aware so declaring this won't
# stop your mod loading on the server for example.
#[features.${mod_id}]
#openGLVersion="[3.2,)"
